esphome:
  name: lms_tag_example
  friendly_name: lms_tag_example

esp32:
  board: esp32dev
  framework:
    type: arduino

# use components from a local folder
external_components:
  - source:
      type: local
      path: components

lms:
  # uniqie id
  id: slimserver
  # server that hosts the LMS
  server: slimserver
  # LMS client/player to control, hex id
  client_id: b8:27:eb:4f:71:11

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

# Include CSS and JS directly to avoid needing Internet
web_server:
  local: true

text_sensor:
  - platform: template
    name: "RFID Tag"
    id: rfid_tag

button:
  - platform: template
    name: "Remove Tag"
    on_press:
      then:
        - text_sensor.template.publish:
            id: rfid_tag
            state: ''
        - lambda: |-
            auto lms = id(slimserver);
            lms->send_tag_removed();
  - platform: template
    name: "Tag 00-00-00-00"
    on_press:
      then:
        - text_sensor.template.publish:
            id: rfid_tag
            state: '00-00-00-00'
        - lambda: |-
            auto lms = id(slimserver);
            lms->send_tag("00-00-00-00");
